# Generated by Django 5.2.13 on 2026-05-17 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('core', '0010_alter_attribute_table_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'template_id',
                    models.CharField(
                        db_comment='identifier of the MCI template used (e.g. debian-12-desktop)',
                        max_length=100,
                        verbose_name='Template ID',
                    ),
                ),
                (
                    'base_os',
                    models.CharField(
                        blank=True,
                        db_comment='base operating system name (e.g. debian, ubuntu)',
                        max_length=255,
                        verbose_name='Base OS',
                    ),
                ),
                (
                    'dockerfile',
                    models.TextField(
                        blank=True,
                        db_comment='jinja2 template for the dockerfile used to build the image',
                        verbose_name='Dockerfile',
                    ),
                ),
                (
                    'partition',
                    models.TextField(
                        blank=True,
                        db_comment='yaml partition schema definition for the image creation',
                        verbose_name='Partition',
                    ),
                ),
                (
                    'project',
                    models.OneToOneField(
                        db_comment='related project for this MCI configuration',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='mci_config',
                        to='core.project',
                        verbose_name='Project',
                    ),
                ),
            ],
            options={
                'verbose_name': 'MCI Config',
                'verbose_name_plural': 'MCI Configs',
                'db_table_comment': 'stores the general MCI configuration template, base operating system and partition schema for a project',
            },
        ),
        migrations.CreateModel(
            name='Flavour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'name',
                    models.CharField(
                        db_comment='name of the flavour (e.g. Desktop, Server, Minimal)',
                        max_length=255,
                        verbose_name='Name',
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True,
                        db_comment='detailed description of the flavour purpose and packages',
                        verbose_name='Description',
                    ),
                ),
                (
                    'tags',
                    models.ManyToManyField(
                        blank=True,
                        related_name='flavours',
                        to='core.ServerAttribute',
                        verbose_name='Tags',
                    ),
                ),
                (
                    'enabled',
                    models.BooleanField(
                        db_comment='indicates if this flavour is active and can be built',
                        default=True,
                        verbose_name='Enabled',
                    ),
                ),
                (
                    'user',
                    models.CharField(
                        db_comment='default user name created in the system', max_length=255, verbose_name='User'
                    ),
                ),
                (
                    'password',
                    models.CharField(
                        db_comment='default user password or hash created in the system',
                        max_length=255,
                        verbose_name='Password',
                    ),
                ),
                (
                    'keymap',
                    models.CharField(
                        db_comment='keyboard layout code (e.g. us, es)',
                        default='us',
                        max_length=50,
                        verbose_name='Keymap',
                    ),
                ),
                (
                    'keyboard_model',
                    models.CharField(
                        db_comment='keyboard hardware model (e.g. pc105)',
                        default='pc105',
                        max_length=50,
                        verbose_name='Keyboard Model',
                    ),
                ),
                (
                    'charmap',
                    models.CharField(
                        db_comment='character set encoding (e.g. UTF-8)',
                        default='UTF-8',
                        max_length=50,
                        verbose_name='Charmap',
                    ),
                ),
                (
                    'codeset',
                    models.CharField(
                        db_comment='console keyboard code set (e.g. guess, Lat15)',
                        default='guess',
                        max_length=50,
                        verbose_name='Codeset',
                    ),
                ),
                (
                    'timezone',
                    models.CharField(
                        db_comment='system timezone name (e.g. Europe/Madrid, UTC)',
                        default='Europe/Madrid',
                        max_length=100,
                        verbose_name='Timezone',
                    ),
                ),
                (
                    'hostname',
                    models.CharField(
                        db_comment='hostname assigned to the built system', max_length=255, verbose_name='Hostname'
                    ),
                ),
                (
                    'config',
                    models.ForeignKey(
                        db_comment='related MCI configuration',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='flavours',
                        to='mci.config',
                        verbose_name='MCI Config',
                    ),
                ),
            ],
            options={
                'verbose_name': 'MCI Flavour',
                'verbose_name_plural': 'MCI Flavours',
                'db_table_comment': 'defines specific system environments or variants (flavours) with customized hostnames, credentials, timezones, and packages',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'name',
                    models.CharField(
                        db_comment='name of the release (e.g. v1.0, 2026-05)', max_length=255, verbose_name='Name'
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True, db_comment='detailed release notes and changelog', verbose_name='Description'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment='timestamp when the release was registered',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'config',
                    models.ForeignKey(
                        db_comment='related MCI configuration',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='releases',
                        to='mci.config',
                        verbose_name='MCI Config',
                    ),
                ),
            ],
            options={
                'verbose_name': 'MCI Release',
                'verbose_name_plural': 'MCI Releases',
                'db_table_comment': 'represents a versioned build release of a specific MCI configuration',
            },
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'task_id',
                    models.CharField(
                        blank=True,
                        db_comment='Redis/Celery task identifier associated with the build process',
                        max_length=255,
                        verbose_name='Task ID',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('queued', 'Queued'),
                            ('running', 'Running'),
                            ('completed', 'Completed'),
                            ('failed', 'Failed'),
                        ],
                        db_comment='current status of the build task (queued, running, completed, failed)',
                        default='queued',
                        max_length=50,
                        verbose_name='Status',
                    ),
                ),
                (
                    'started_at',
                    models.DateTimeField(
                        blank=True,
                        db_comment='timestamp when the build process started',
                        null=True,
                        verbose_name='Started At',
                    ),
                ),
                (
                    'finished_at',
                    models.DateTimeField(
                        blank=True,
                        db_comment='timestamp when the build process ended',
                        null=True,
                        verbose_name='Finished At',
                    ),
                ),
                (
                    'uri',
                    models.TextField(
                        blank=True, db_comment='download URI of the generated system image files', verbose_name='URI'
                    ),
                ),
                (
                    'size',
                    models.BigIntegerField(
                        blank=True,
                        db_comment='total size in bytes of the generated system image',
                        null=True,
                        verbose_name='Size',
                    ),
                ),
                (
                    'log',
                    models.TextField(
                        blank=True,
                        db_comment='stdout and stderr compilation logs from the build task',
                        verbose_name='Log',
                    ),
                ),
                (
                    'flavour',
                    models.ForeignKey(
                        db_comment='related flavour built in this task',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='builds',
                        to='mci.flavour',
                        verbose_name='Flavour',
                    ),
                ),
                (
                    'release',
                    models.ForeignKey(
                        db_comment='related release associated with this build',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='builds',
                        to='mci.release',
                        verbose_name='Release',
                    ),
                ),
            ],
            options={
                'verbose_name': 'MCI Build',
                'verbose_name_plural': 'MCI Builds',
                'db_table_comment': 'tracks individual build tasks of a release and flavour, including status, compilation logs, image size and download URL',
            },
        ),
    ]
