# Generated by Django 5.2.9 on 2026-06-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgi', '0002_alter_flavour_config_alter_release_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='published',
            field=models.BooleanField(db_comment='indicates if the golden image generated by this build is published and enabled in the public catalog', default=False, verbose_name='Published'),
        ),
    ]
